### ISSUE TITLE
Move to rust-lang/rustc-timing

### ISSUE THREAD

**Issue by Mark-Simulacrum** [jonhoo/rust-at-sunrise#3]
https://github.com/jonhoo/rust-at-sunrise/blob/b9c5a39da65d92deabc1ddc6857f3bb4d115c438/src/main.rs#L269

The timing data has moved to the rust-lang organization (the old location is no longer updated). The format of the data has not changed, though, so this is hopefully a relatively easy update; we've also erased all old data so you should be able to free up some disk space as well if you want :)

**Comment by jonhoo** [comment]
Now that I access the files directly from `raw.githubusercontent.com`, I luckily don't have to store them all locally any more, but I'll update the URL, thanks!
